# action.yml
name: 'Markdown FAQ'
description: 'This action converts your issue to a markdown file for an FAQ'
inputs:
  issue_context:  # id of input
    description: 'FAQ Issue'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    action: ${{ inputs.action }}
    # created_at: ${{ inputs.issue_context }}
    # updated_at: ${{ inputs.issue_context }}
    # login: ${{ inputs.issue_context }}
    # body: ${{ inputs.issue_context }}
