# action.yml
name: 'Markdown FAQ'
description: 'This action converts your issue to a markdown file for an FAQ'
inputs:
  issue_context:  # id of input
    description: 'FAQ Issue'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    action: ${{ inputs.action }}
    created_at: ${{ inputs.created_at }}
    updated_at: ${{ inputs.updated_at }}
    login: ${{ inputs.login }}
    body: ${{ inputs.body }}
