# action.yml
name: 'Markdown FAQ'
description: 'This action converts your issue to a markdown file for an FAQ'
inputs:
  directory:
    description: 'The directory you want your FAQs stored in'
    required: true
    default: '/faq/'
  title: 
    description: 'This is the question'
    required: true
    default: ''
  action:
    description: 'action of the issue (opened or edited)'
    required: true
    default: ''
  created_at:
    description: 'when the issue was created'
    required: true
    default: ''
  updated_at:
    description: 'when the issue was updated'
    required: true
    default: ''
  login:
    description: 'the user that created the issue'
    required: true
    default: ''
  body:
    description: 'contents of the body'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    title: ${{ inputs.title }}
    action: ${{ inputs.action }}
    created_at: ${{ inputs.created_at }}
    updated_at: ${{ inputs.updated_at }}
    login: ${{ inputs.login }}
    body: ${{ inputs.body }}
